// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1:string):Promise<string>;

export function ProcessData(arg1:any):Promise<void>;

export function ReadSettings():Promise<string>;

export function SelectFiles():Promise<void>;

export function SelectOutputFolder():Promise<void>;

export function SelectWatermark():Promise<void>;
