// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ProcessData(arg1) {
  return window['go']['main']['App']['ProcessData'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function SelectFiles() {
  return window['go']['main']['App']['SelectFiles']();
}

export function SelectOutputFolder() {
  return window['go']['main']['App']['SelectOutputFolder']();
}

export function SelectWatermark() {
  return window['go']['main']['App']['SelectWatermark']();
}

export function Shutdown(arg1) {
  return window['go']['main']['App']['Shutdown'](arg1);
}
